import logging
from config import db_path
import sqlite3
from datetime import datetime

logger = logging.getLogger(__name__)

connection = sqlite3.connect(db_path())
cursor = connection.cursor()


def db_create_emote(user_id, emote, mood=0):
    """
        emote_structure = {
            'id': i[0], autogenerated
            'user_id': i[1], // internal fw id
            'emote': text
            'date': now()
            'mood': -1/0/1

    1. update date as of now()
    2. insert data in the tb Emotes"""

    emote_date = datetime.today().isoformat()

    with connection:
        cursor.execute('''INSERT INTO Emotes (user_id, emote_date, emote, mood) VALUES (?, ? , ? , ?)
            ''', (user_id, emote_date, emote, mood))
